# Package initializer for routes module
from .oauth import router as oauth_router
from .wallet import router as wallet_router
from .git import router as git_router
from .troubleshoot import router as troubleshoot_router
from .quantum_link import router as quantum_link_router
from .mcp_protocol import router as mcp_protocol_router
from .credentials import router as credentials_router
from .void import router as void_router
