name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r vial2/requirements.txt
      - name: Run tests
        run: |
          pytest vial2/tests/
      - name: Build Docker image
        run: |
          docker build -t vial2-mcp:latest .
      - name: Push Docker image
        if: github.event_name == 'push'
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker push vial2-mcp:latest
      - name: Deploy to Netlify
        if: github.event_name == 'push'
        run: |
          netlify deploy --prod --dir vial2/netlify --auth ${{ secrets.NETLIFY_AUTH_TOKEN }} --site ${{ secrets.NETLIFY_SITE_ID }}
      - name: Check database migrations
        if: github.event_name == 'push'
        run: |
          python vial2/mcp/database/migrate.py

# xAI Artifact Tags: #vial2 #mcp #ci_cd #github #neon_mcp
