#!/usr/bin/env python3
"""
MSPYB-style minimal bootstrap example (illustrative, not production).
LLM-INSTRUCTION: This file is the single source of truth. Edit only here.
MSPYB_VERSION = 3.0.0-demo
"""

from __future__ import annotations
import argparse
import logging
import os
import platform
import subprocess
import sys
from pathlib import Path
from string import Template

MSPYB_VERSION = "3.0.0-demo"

TEMPLATE_VARS = {
    "PROJECT_NAME": "demo_app",
    "API_PORT": "8080",
    "AUTO_LAUNCH": "false",          # set "true" to auto-start
    "LAUNCH_COMMAND": "python -m app.main",
    "LAUNCH_CWD": ".",
}

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
    datefmt="%H:%M:%S",
)
log = logging.getLogger("bootstrap")


def detect_environment() -> dict:
    return {
        "os": platform.system(),
        "arch": platform.machine(),
        "python": sys.version.split()[0],
        "has_docker": subprocess.call(
            ["docker", "info"], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL
        )
        == 0,
    }


def write_file(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    rendered = Template(content).safe_substitute(TEMPLATE_VARS)
    path.write_text(rendered, encoding="utf-8")
    log.info("Wrote %s", path)


def generate(project_root: Path) -> None:
    write_file(
        project_root / "VERSION",
        MSPYB_VERSION + "\n",
    )
    write_file(
        project_root / "app" / "main.py",
        '''\
"""Demo application entry point."""
import http.server
import socketserver

PORT = int("$API_PORT")

class Handler(http.server.SimpleHTTPRequestHandler):
    def do_GET(self):
        self.send_response(200)
        self.send_header("Content-type", "text/plain")
        self.end_headers()
        self.wfile.write(b"Hello from MSPYB demo on port $API_PORT\\n")

if __name__ == "__main__":
    with socketserver.TCPServer(("", PORT), Handler) as httpd:
        print(f"Serving on port {PORT}")
        httpd.serve_forever()
''',
    )
    write_file(
        project_root / "README.md",
        "# $PROJECT_NAME\n\nGenerated by MSPYB bootstrap $MSPYB_VERSION.\n",
    )


def auto_launch(project_root: Path, env: dict) -> None:
    if TEMPLATE_VARS["AUTO_LAUNCH"].lower() != "true":
        log.info("Auto-launch disabled")
        return
    cwd = project_root / TEMPLATE_VARS["LAUNCH_CWD"]
    cmd = TEMPLATE_VARS["LAUNCH_COMMAND"]
    log.info("Launching: %s (cwd=%s)", cmd, cwd)
    try:
        subprocess.Popen(cmd, shell=True, cwd=cwd)
        log.info("Launch attempted")
    except Exception as e:
        log.error("Launch failed: %s — recovery: verify LAUNCH_COMMAND and environment", e)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--skip-installs", action="store_true")
    parser.add_argument("--no-launch", action="store_true")
    args = parser.parse_args()

    env = detect_environment()
    log.info("Environment: %s", env)

    if not args.skip_installs:
        log.info("INSTALLS: (demo — no packages required)")

    project_root = Path.cwd() / TEMPLATE_VARS["PROJECT_NAME"]
    generate(project_root)

    if not args.no_launch:
        auto_launch(project_root, env)
    else:
        log.info("Auto-launch skipped by --no-launch")

    print(f"\nBootstrap complete. Project at {project_root}")
    print(f"MSPYB_VERSION={MSPYB_VERSION}")


if __name__ == "__main__":
    main()
