name: Vial MCP CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis:6.2
        ports:
          - 6379:6379

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: pip install -r main/server/requirements.txt
    - name: Lint Python
      run: pylint main/server/mcp/*.py
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    - name: Install frontend dependencies
      run: npm install --prefix main/pages
    - name: Lint JavaScript
      run: eslint main/pages/*.js main/pages/api/*.js main/server/vial/static/*.js
    - name: Run tests
      run: pytest main/server/mcp/test_*.py
    - name: Build Docker image
      run: docker build -t vial-mcp:latest .
    - name: Run Docker Compose
      run: docker-compose up -d
    - name: Test API
      run: |
        sleep 10
        curl --insecure -X GET https://localhost:8000/api/health
