name: Vial MCP CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        pip install -r db/requirements.txt
    - name: Run tests
      run: |
        pytest vial/tests/
    - name: Build Docker
      run: |
        docker build -t vial-mcp .
    - name: Run Docker
      run: |
        docker-compose up -d
    - name: Check health
      run: |
        curl --fail http://localhost:8000/api/health
    env:
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      MONGODB_URI: mongodb://mongo:27017
      REDIS_HOST: redis:6379
