version: '3.8'
services:
  backend:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - mongo
      - redis
    volumes:
      - .:/app
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
  redis:
    image: redis:7.0
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
  node:
    build:
      context: ./node
    ports:
      - "3000:3000"
    volumes:
      - ./node:/app
volumes:
  mongo_data:
  redis_data:
