version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - AUTH_API_KEY=${AUTH_API_KEY}
      - GROK_API_KEY=${GROK_API_KEY}
      - GIT_REPO_PATH=${GIT_REPO_PATH}
      - NEON_DB_URL=${NEON_DB_URL}
      - WEBXOS_TOKEN=${WEBXOS_TOKEN}
    volumes:
      - .:/app
    depends_on:
      - db
  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=vial2
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
