version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=mongodb://mongo:27017
    volumes:
      - .:/app
    depends_on:
      - mongo
    command: ["./wait-for-it.sh", "mongo:27017", "--", "uvicorn", "unified_server:app", "--host", "0.0.0.0", "--port", "8000"]

  mongo:
    image: mongo:5.0
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=webxos

  web:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./public:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api

volumes:
  mongo_data:
