version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./main/server/vial/static:/app/main/server/vial/static
      - ./main/server/mcp:/app/main/server/mcp
      - ./main/pages:/app/main/pages
      - ./main/server/docs:/app/main/server/docs
      - ./main/server/prompts:/app/main/server/prompts
      - ./notes:/app/notes
      - ./certs:/app/certs
      - ./vial_mcp.db:/app/vial_mcp.db
      - ./backups:/app/backups
    environment:
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - API_KEY=${API_KEY}
    depends_on:
      - redis
  redis:
    image: redis:6.2
    ports:
      - "6379:6379"
  frontend:
    image: node:18
    working_dir: /app/main/pages
    command: npm run dev
    ports:
      - "3000:3000"
    volumes:
      - ./main/pages:/app/main/pages
    depends_on:
      - backend
volumes:
  notes:
  certs:
  vial_mcp.db:
  backups:
