version: '3.8'
services:
  backend:
    build:
      context: ./vial
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./errorlog.md:/app/errorlog.md
      - ./wallet.db:/app/wallet.db
    environment:
      - MCP_HOST=0.0.0.0
      - MCP_PORT=5000
      - API_TOKEN=secret-token
      - WEB3_PROVIDER=${WEB3_PROVIDER}
  db:
    image: sqlite:latest
    volumes:
      - ./wallet.db:/data/wallet.db