version: '3.8'
services:
  frontend:
    build:
      context: ./main/frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    networks:
      - vial-mcp-network
  backend:
    build:
      context: ./main/api
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    environment:
      - NEON_DATABASE_URL=${NEON_DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - db
    networks:
      - vial-mcp-network
  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=vialmcp
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=vialmcp
    volumes:
      - ./main/api/mcp/database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - "5432:5432"
    networks:
      - vial-mcp-network
networks:
  vial-mcp-network:
    driver: bridge
