version: '3.8'
services:
  frontend:
    build:
      context: ./main/frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - NODE_ENV=development
    volumes:
      - ./main/frontend/public:/app/public
    networks:
      - vial-mcp-network

  backend:
    build:
      context: ./main/api/mcp
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    environment:
      - NODE_ENV=development
      - NEON_DATABASE_URL=${NEON_DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
    volumes:
      - ./main/api/mcp:/app
      - ./main/api/mcp/logs:/app/logs
    depends_on:
      - db
    networks:
      - vial-mcp-network

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=vialmcp
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=vialmcp
    ports:
      - "5432:5432"
    volumes:
      - ./main/api/mcp/database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - pgdata:/var/lib/postgresql/data
    networks:
      - vial-mcp-network

networks:
  vial-mcp-network:
    driver: bridge

volumes:
  pgdata:
