version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=mongodb://mongo:27017
    depends_on:
      redis:
        condition: service_healthy
    volumes:
      - ./notes:/app/notes
      - ./certs:/app/certs
      - ./vial_mcp.db:/app/vial_mcp.db
    command: ["./wait-for-it.sh","redis:6379","--","python","main/server/unified_server.py"]
    networks:
      - vial-network
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD","redis-cli","ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - vial-network
networks:
  vial-network:
    driver: bridge
volumes:
  notes:
  certs:
  vial_mcp_db:
