[build]
  publish = "main/frontend/public"
  command = "npm run build"

[context.production.environment]
  DATABASE_URL = "${DATABASE_URL}"
  GITHUB_CLIENT_ID = "${GITHUB_CLIENT_ID}"
  GITHUB_CLIENT_SECRET = "${GITHUB_CLIENT_SECRET}"
  REDIS_URL = "${REDIS_URL}"
  SMTP_SERVER = "${SMTP_SERVER}"
  SMTP_PORT = "${SMTP_PORT}"
  SMTP_USER = "${SMTP_USER}"
  SMTP_PASSWORD = "${SMTP_PASSWORD}"
  ALERT_EMAIL = "${ALERT_EMAIL}"

[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' https://github.com; style-src 'self' 'unsafe-inline'; connect-src 'self' wss://webxos.netlify.app https://api.github.com; img-src 'self';"

[[redirects]]
  from = "/mcp/*"
  to = "/.netlify/functions/api"
  status = 200
  force = true
