[build]
  command = "npm install && npm run build"
  functions = "main/netlify/functions"
  publish = "main/frontend/public"

[[redirects]]
  from = "/mcp/*"
  to = "/.netlify/functions/api"
  status = 200
  force = true

[[redirects]]
  from = "/auth/callback"
  to = "/index.html"
  status = 200

[functions]
  node_bundler = "esbuild"

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; script-src 'self' https://*.github.com; connect-src 'self' ws://localhost:8000 https://*.github.com;"
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"

[context.production.environment]
  DATABASE_URL = ":env(DATABASE_URL)"
  GITHUB_CLIENT_ID = ":env(GITHUB_CLIENT_ID)"
  GITHUB_CLIENT_SECRET = ":env(GITHUB_CLIENT_SECRET)"
