[build]
  command = "npm install"
  functions = "main/api/mcp/netlify/functions"
  publish = "main/frontend/public"

[[redirects]]
  from = "/.netlify/functions/*"
  to = "/main/api/mcp/netlify/functions/:splat"
  status = 200
  force = true

[functions]
  node_bundler = "esbuild"
