# Netlify configuration for WEBXOS MCP Gateway
[build]
  publish = "main"
  command = ""

[[redirects]]
  from = "/v1/*"
  to = "https://vial-mcp-backend.onrender.com/:splat"
  status = 200
  force = true
  headers = { "X-From" = "Netlify" }

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
