[build]
  command = "pip install -r requirements.txt"
  publish = "dist"

[[redirects]]
  from = "/v1/*"
  to = "https://vial-mcp-backend.onrender.com/v1/:splat"
  status = 200
  force = true
  headers = { 
    "X-From" = "Netlify",
    "Accept" = "application/json",
    "Content-Type" = "application/json"
  }

[[redirects]]
  from = "/api/*"
  to = "https://vial-mcp-backend.onrender.com/v1/:splat"
  status = 200
  force = true
  headers = { 
    "X-From" = "Netlify",
    "Accept" = "application/json",
    "Content-Type" = "application/json"
  }

[[redirects]]
  from = "/ws"
  to = "wss://vial-mcp-backend.onrender.com/ws"
  status = 200
  force = true
  headers = { "X-From" = "Netlify" }

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
