[build]
  command = "pip install -r requirements.txt"
  publish = "dist"

# Proxy API requests to the FastAPI backend
# Replace 'http://localhost:8000' with your deployed backend URL (e.g., 'https://vial-mcp-backend.onrender.com')
[[redirects]]
  from = "/v1/*"
  to = "http://localhost:8000/v1/:splat"
  status = 200
  force = true
  headers = { 
    "X-From" = "Netlify",
    "Accept" = "application/json",
    "Content-Type" = "application/json"
  }

[[redirects]]
  from = "/api/*"
  to = "http://localhost:8000/v1/:splat"
  status = 200
  force = true
  headers = { 
    "X-From" = "Netlify",
    "Accept" = "application/json",
    "Content-Type" = "application/json"
  }

# Proxy WebSocket requests
[[redirects]]
  from = "/ws"
  to = "ws://localhost:8000/ws"
  status = 200
  force = true
  headers = { "X-From" = "Netlify" }

# Health check endpoint to verify backend connectivity
[[redirects]]
  from = "/health"
  to = "http://localhost:8000/health"
  status = 200
  force = true
  headers = { 
    "X-From" = "Netlify",
    "Accept" = "application/json"
  }

# Serve frontend for non-API routes
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
