[[redirects]]
  from = "/v1/*"
  to = "https://webxos-mcp-gateway.onrender.com/:splat"
  status = 200
  force = true
  headers = { "Accept" = "application/json", "Content-Type" = "application/json" }

[[redirects]]
  from = "/*"
  to = "/main/index.html"
  status = 200
