[build]
  command = "pip install -r requirements.txt"
  publish = "dist"

[[redirects]]
  from = "/v1/*"
  to = "http://your-backend-url:8000/v1/:splat"
  status = 200
  force = true
  headers = { "X-From" = "Netlify" }

[[redirects]]
  from = "/ws"
  to = "ws://your-backend-url:8000/ws"
  status = 200
  force = true
  headers = { "X-From" = "Netlify" }

[[redirects]]
  from = "/api/*"
  to = "http://your-backend-url:8000/v1/:splat"
  status = 200
  force = true
  headers = { "X-From" = "Netlify" }

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
