[build]
  command = "pip install -r requirements.txt && python -m build"
  publish = "dist"

[[redirects]]
  from = "/v1/*"
  to = "http://your-backend-url:8000/v1/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/ws"
  to = "ws://your-backend-url:8000/ws"
  status = 200
  force = true
