FROM python:3.9-slim

WORKDIR /app/db

COPY db/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY db/ .

EXPOSE 8001

CMD ["sh", "wait-for-it.sh", "mongo:27017", "--", "python", "server.py"]
