version: '3.8'
services:
  vial2:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - STACK_AUTH_CLIENT_ID=${STACK_AUTH_CLIENT_ID}
      - STACK_AUTH_CLIENT_SECRET=${STACK_AUTH_CLIENT_SECRET}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - NETLIFY_SITE_ID=${NETLIFY_SITE_ID}
      - NETLIFY_AUTH_TOKEN=${NETLIFY_AUTH_TOKEN}
    volumes:
      - ./error_log.db:/app/error_log.db
    depends_on:
      - neon
  neon:
    image: neondatabase/neon-proxy:latest
    environment:
      - NEON_PROJECT_ID=${NEON_PROJECT_ID}
      - NEON_API_KEY=${NEON_API_KEY}
    ports:
      - "5432:5432"

# xAI Artifact Tags: #vial2 #docker #neon_mcp
