version: '3.8'
services:
  vial2:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - NEON_API_KEY=${NEON_API_KEY}
      - NETLIFY_AUTH_TOKEN=${NETLIFY_AUTH_TOKEN}
      - NETLIFY_SITE_ID=${NETLIFY_SITE_ID}
    volumes:
      - .:/app
    depends_on:
      - neon
    command: uvicorn mcp.server:app --host 0.0.0.0 --port 8000 --reload

  neon:
    image: neondatabase/neon:latest
    environment:
      - NEON_PROJECT_ID=${NEON_PROJECT_ID}
      - DATABASE_URL=${DATABASE_URL}
    ports:
      - "5432:5432"
    volumes:
      - neon_data:/var/lib/neon

volumes:
  neon_data:
