[build]
  command = "pip install -r vial2/requirements.txt"
  publish = "."
  functions = "vial2"

[context.production.environment]
  DATABASE_URL = "${DATABASE_URL}"
  STACK_AUTH_CLIENT_ID = "${STACK_AUTH_CLIENT_ID}"
  STACK_AUTH_CLIENT_SECRET = "${STACK_AUTH_CLIENT_SECRET}"
  JWT_SECRET_KEY = "${JWT_SECRET_KEY}"
  NETLIFY_SITE_ID = "${NETLIFY_SITE_ID}"
  NETLIFY_AUTH_TOKEN = "${NETLIFY_AUTH_TOKEN}"

# xAI Artifact Tags: #vial2 #netlify #neon_mcp
