openapi: 3.0.3
info:
  title: WEBXOS MCP Gateway
  description: API Gateway for WEBXOS Vial MCP (BETA)
  version: 2.7.8
servers:
  - url: https://vial-mcp-backend.onrender.com/v1
paths:
  /health:
    get:
      summary: Health Check
      responses:
        '200':
          description: Health check successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  status: { type: string }
                  balance: { type: number }
                  reputation: { type: integer }
        '500':
          description: Health check failed
  /wallet:
    get:
      summary: Get Wallet Data
      security:
        - OAuth2PasswordBearer: []
      responses:
        '200':
          description: Wallet data retrieved
          content:
            application/json:
              schema:
                type: object
                properties:
                  wallet_key: { type: string }
                  session_balance: { type: number }
                  address: { type: string }
                  vial_agent: { type: string }
                  quantum_state: { type: object }
        '401':
          description: Unauthorized
        '500':
          description: Wallet service unavailable
  /oauth/token:
    post:
      summary: Generate OAuth Token
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                grant_type: { type: string }
                client_id: { type: string }
                client_secret: { type: string }
              required: [grant_type, client_id, client_secret]
      responses:
        '200':
          description: Token generated
          content:
            application/json:
              schema:
                type: object
                properties:
                  access_token: { type: string }
                  token_type: { type: string }
                  expires_in: { type: integer }
        '401':
          description: Invalid credentials
        '500':
          description: Authentication error
  /generate-credentials:
    post:
      summary: Generate API Credentials
      security:
        - OAuth2PasswordBearer: []
      responses:
        '200':
          description: Credentials generated
          content:
            application/json:
              schema:
                type: object
                properties:
                  key: { type: string }
                  secret: { type: string }
        '401':
          description: Unauthorized
        '500':
          description: Credential error
  /void:
    post:
      summary: Void Transaction
      security:
        - OAuth2PasswordBearer: []
      responses:
        '200':
          description: Transaction voided
        '401':
          description: Unauthorized
        '500':
          description: Void error
  /troubleshoot:
    get:
      summary: Run Diagnostics
      security:
        - OAuth2PasswordBearer: []
      responses:
        '200':
          description: Diagnostics completed
        '401':
          description: Unauthorized
        '500':
          description: Troubleshoot error
  /quantum-link:
    get:
      summary: Establish Quantum Link
      security:
        - OAuth2PasswordBearer: []
      responses:
        '200':
          description: Quantum link established
        '401':
          description: Unauthorized
        '500':
          description: Quantum link error
  /mcp/rpc:
    post:
      summary: MCP Protocol RPC
      security:
        - OAuth2PasswordBearer: []
      responses:
        '200':
          description: MCP protocol initialized
        '401':
          description: Unauthorized
        '500':
          description: MCP protocol error
components:
  securitySchemes:
    OAuth2PasswordBearer:
      type: oauth2
      flows:
        password:
          tokenUrl: /v1/oauth/token
          scopes: {}
