# main/server/mcp/docker-compose.yml
version: '3.8'
services:
  mcp-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/vial_mcp
      - REDIS_URI=redis://redis:6379
      - SECRET_KEY=${SECRET_KEY}
      - RATE_LIMIT_REQUESTS=100
      - RATE_LIMIT_WINDOW_SECONDS=60
      - CACHE_TTL_SECONDS=3600
    depends_on:
      - mongo
      - redis
    volumes:
      - ./:/app
    networks:
      - mcp-network

  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - mcp-network

  redis:
    image: redis:7.0
    ports:
      - "6379:6379"
    networks:
      - mcp-network

networks:
  mcp-network:
    driver: bridge

volumes:
  mongo-data:
