# main/server/kubernetes/manifests/mcp_deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vial-mcp-server
  labels:
    app: vial-mcp-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: vial-mcp-server
  template:
    metadata:
      labels:
        app: vial-mcp-server
    spec:
      containers:
      - name: mcp-server
        image: vial/mcp-server:latest
        ports:
        - containerPort: 8080
        env:
        - name: MCP_SERVER_HOST
          value: "0.0.0.0"
        - name: MCP_SERVER_PORT
          value: "8080"
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: vial-secrets
              key: mongodb-uri
        - name: REDIS_URI
          valueFrom:
            secretKeyRef:
              name: vial-secrets
              key: redis-uri
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: vial-mcp-service
spec:
  selector:
    app: vial-mcp-server
  ports:
  - port: 80
    targetPort: 8080
  type: LoadBalancer
