# main/server/mcp/kubernetes/manifests/mcp_deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vial-mcp-controller
  namespace: mcp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: vial-mcp-controller
  template:
    metadata:
      labels:
        app: vial-mcp-controller
    spec:
      containers:
      - name: mcp-server
        image: vial-mcp-controller:latest
        ports:
        - containerPort: 8080
        env:
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: mcp-secrets
              key: mongodb-uri
        - name: REDIS_URI
          valueFrom:
            secretKeyRef:
              name: mcp-secrets
              key: redis-uri
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: mcp-secrets
              key: secret-key
        resources:
          limits:
            cpu: "1"
            memory: "512Mi"
          requests:
            cpu: "0.5"
            memory: "256Mi"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: vial-mcp-service
  namespace: mcp
spec:
  selector:
    app: vial-mcp-controller
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: ClusterIP
