[[redirects]]
  from = "/chatbot/*"
  to = "/chatbot/chatbot.html"
  status = 200

[build]
  base = ""
  publish = "chatbot"
  command = ""

[[headers]]
  for = "/chatbot/*"
  [headers.values]
    Content-Type = "text/html; charset=UTF-8"
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/chatbot/*.js"
  [headers.values]
    Content-Type = "application/javascript; charset=UTF-8"
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/chatbot/*.css"
  [headers.values]
    Content-Type = "text/css; charset=UTF-8"
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/chatbot/*.json"
  [headers.values]
    Content-Type = "application/json; charset=UTF-8"
    Cache-Control = "public, max-age=31536000, immutable"
