version: '3.8'

services:
  hive:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./static:/app/static
      - ./logs:/app/logs
      - ./users.txt:/app/users.txt
    environment:
      - PYTHONUNBUFFERED=1