[build]
  command = "npm run build"
  publish = "main/app"
  functions = "server/mcp/functions"

[[redirects]]
  from = "/vial2/api/troubleshoot"
  to = "/.netlify/functions/troubleshoot"
  status = 200
  force = true

[[redirects]]
  from = "/vial2/api/auth/oauth"
  to = "/.netlify/functions/auth"
  status = 200
  force = true

[[headers]]
  for = "/vial2/api/*"
  [headers.values]
    Content-Type = "application/json"
    X-Content-Type-Options = "nosniff"
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type"

[dev]
  command = "npm run dev"
  port = 8888
  targetPort = 3000

[functions]
  node_bundler = "esbuild"
  included_files = ["server/mcp/utils/*"]
  timeout = 30
  external_node_modules = ["fs"]
  [functions.settings]
    no_cache = true
    ignore_paths = ["*.html"]
