[build]
  command = "npm run build"
  publish = "main/app"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/vial2/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[headers]]
  for = "/api/*"
  [headers.values]
    Content-Type = "application/json"
    X-Content-Type-Options = "nosniff"
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type"

[dev]
  command = "npm run dev"
  port = 8888
  targetPort = 3000

[functions]
  node_bundler = "esbuild"
  included_files = ["server/mcp/utils/*"]
  timeout = 30
  external_node_modules = ["fs"]
  [functions.settings]
    no_cache = true
    serve = true
