# main/server/mcp/config/prometheus.yml
global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'vial_mcp'
    static_configs:
      - targets: ['localhost:8000']
    metrics_path: '/metrics'
    basic_auth:
      username: 'admin'
      password: 'vial_mcp_prometheus'
  - job_name: 'redis'
    static_configs:
      - targets: ['localhost:6379']
  - job_name: 'mongodb'
    static_configs:
      - targets: ['localhost:27017']
